### ISSUE TITLE
Organize resources better in README

### ISSUE THREAD

**Issue by omjogani** [NisargPipaliya/TechTitans#116]
### Checklist
- [x] Organize resource (links) in the table as described below (AI-Generated) Feel free to edit it.

### AI-Modified README

---

# TechTitans 🌎⚡

[![TechTitans](https://img.shields.io/badge/Tech-Titans-brightgreen?style=for-the-badge)](https://github.com/yourusername/TechTitans)

Welcome to the TechTitans repository, your one-stop destination for enriching resources and guides in the world of technology. 🚀

## Data Structures and Algorithms 📚

| Resource | Link |
|----------|------|
| Take You Forward | [![Take You Forward](https://img.shields.io/badge/Take-You%20Forward-blue?style=flat-square&logo=data:image/png;base64,...)](https://takeuforward.org/) |

## Microservices Course 🛠️

| Part | Link |
|------|------|
| Part 1 | [![YouTube](https://img.shields.io/badge/YouTube-red?style=flat-square&logo=youtube&logoColor=white)](https://youtu.be/BLlEgtp2_i8) |
| Part 2 | [![YouTube](https://img.shields.io/badge/YouTube-red?style=flat-square&logo=youtube&logoColor=white)](https://www.youtube.com/watch?v=EeQRAxXWDF4&t=0s) |

## Docker 🐳

| Resource | Link |
|----------|------|
| RoadMap | [![RoadMap](https://img.shields.io/badge/RoadMap-brightgreen?style=flat-square&logo=data:image/png;base64,...)](https://roadmap.sh/docker) |
| Tech with Nana | [![YouTube](https://img.shields.io/badge/YouTube-red?style=flat-square&logo=youtube&logoColor=white)](https://youtu.be/3c-iBn73dDE) |
| What is Docker? | [![AWS](https://img.shields.io/badge/AWS-orange?style=flat-square&logo=amazon-aws&logoColor=white)](https://aws.amazon.com/docker/) |

## Kubernetes ☁️

| Resource | Link |
|----------|------|
| RoadMap | [![RoadMap](https://img.shields.io/badge/RoadMap-brightgreen?style=flat-square&logo=data:image/png;base64,...)](https://roadmap.sh/kubernetes) |
| Tech with Nana | [![YouTube](https://img.shields.io/badge/YouTube-red?style=flat-square&logo=youtube&logoColor=white)](https://www.youtube.com/watch?v=X48VuDVv0do) |
| Source Code | [![GitLab](https://img.shields.io/badge/GitLab-orange?style=flat-square&logo=gitlab&logoColor=white)](https://gitlab.com/nanuchi/youtube-tutorial-series/-/tree/master) |
| Kubernetes Handbook | [![K8s](https://img.shields.io/badge/Kubernetes-blue?style=flat-square&logo=kubernetes&logoColor=white)](https://minikube.sigs.k8s.io/docs/handbook/) |
| Using Local Docker Container for K8s Deployment | [![Baeldung](https://img.shields.io/badge/Baeldung-brightgreen?style=flat-square&logo=data:image/png;base64,...)](https://www.baeldung.com/ops/docker-local-images-minikube#:~:text=Let's%20use%20our%20Dockerfile%20and,:%20$%20kubectl%20logs%20first%2Dcontainer) |
| Local Docker Image with minikube | [![BetterStack](https://img.shields.io/badge/BetterStack-blue?style=flat-square&logo=data:image/png;base64,...)](https://betterstack.com/community/questions/how-to-use-local-docker-images-with-minikube/) |
| Good GitHub Repo | [![GitHub](https://img.shields.io/badge/GitHub-181717?style=flat-square&logo=github&logoColor=white)](https://github.com/devopsproin/certified-kubernetes-administrator/tree/main) |

### Helm 

| Resource | Link |
|----------|------|
| Install Helm | [![Helm](https://img.shields.io/badge/Helm-0F1689?style=flat-square&logo=helm&logoColor=white)](https://helm.sh/docs/intro/install/) |
| Helm Hub | [![Artifact Hub](https://img.shields.io/badge/Artifact%20Hub-blue?style=flat-square&logo=data:image/png;base64,...)](https://artifacthub.io/) |
| Helm-GitHub | [![GitHub](https://img.shields.io/badge/GitHub-181717?style=flat-square&logo=github&logoColor=white)](https://github.com/helm) |

## DevOps Playlist 🛠️

| Resource | Link |
|----------|------|
| RoadMap | [![RoadMap](https://img.shields.io/badge/RoadMap-brightgreen?style=flat-square&logo=data:image/png;base64,...)](https://roadmap.sh/devops) |
| Kunal Kushwaha | [![YouTube](https://img.shields.io/badge/YouTube-red?style=flat-square&logo=youtube&logoColor=white)](https://youtube.com/playlist?list=PL9gnSGHSqcnoqBXdMwUTRod4Gi3eac2Ak&si=p1iwhiB2o-zKkIR0) |
| Devops Interview Questions | [Devops Interview Questions](https://www.eccouncil.org/cybersecurity-exchange/devsecops/a-guide-to-devops-interview-questions/) |

## Jira 📝

| Resource | Link |
|----------|------|
| Tutorial | [![YouTube](https://img.shields.io/badge/YouTube-red?style=flat-square&logo=youtube&logoColor=white)](https://www.youtube.com/watch?v=nHuhojfjeUY) |
| GitHub Projects | GitHub projects is similar to Jira kanban dashboard. |
| Flexibility | Jira offers more flexibility; integrate apps like GitHub, Slack, Google Sheets, etc. |
| Limitation | GitHub project is limited to GitHub. |

## Git 🌿

| Resource | Link |
|----------|------|
| Free Code Camp | [![YouTube](https://img.shields.io/badge/YouTube-red?style=flat-square&logo=youtube&logoColor=white)](https://www.youtube.com/watch?v=zTjRZNkhiEU) |

## Python 🐍

| Resource | Link |
|----------|------|
| Cheat Sheet | [![Python Cheat Sheet](https://img.shields.io/badge/Python-Cheat%20Sheet-green?style=flat-square&logo=python&logoColor=white)](https://www.pythoncheatsheet.org/) |
| Python Collection Module | [![Real Python](https://img.shields.io/badge/Real-Python-yellow?style=flat-square&logo=python&logoColor=white)](https://realpython.com/python-collections-module/) |

## GitHub Actions 🔄

| Resource | Link |
|----------|------|
| glich.stream | [![YouTube](https://img.shields.io/badge/YouTube-red?style=flat-square&logo=youtube&logoColor=white)](https://youtube.com/playlist?list=PLArH6NjfKsUhvGHrpag7SuPumMzQRhUKY&si=neQdbgUpow-ahIFf) |
| GitHub Docs | [![GitHub Docs](https://img.shields.io/badge/GitHub-Docs-181717?style=flat-square&logo=github&logoColor=white)](https://docs.github.com/en/actions) |

## YML 📝

| Resource | Link |
|----------|------|
| Blog | [![Spacelift](https://img.shields.io/badge/Spacelift-brightgreen?style=flat-square&logo=data:image/png;base64,...)](https://spacelift.io/blog/yaml) |
| YAML Basics | [![CircleCI](https://img.shields.io/badge/CircleCI-343434?style=flat-square&logo=circleci&logoColor=white)](https://circleci.com/blog/what-is-yaml-a-beginner-s-guide/) |

## Ansible ⚙️

| Resource | Link |
|----------|------|
| Rahul Wagh | [![YouTube](https://img.shields.io/badge/YouTube-red?style=flat-square&logo=youtube&logoColor=white)](https://www.youtube.com/watch?v=GROqwFFLl3s) |
| Ansible Docs | [![Ansible Docs](https://img.shields.io/badge/Ansible-Docs-EE0000?style=flat-square&logo=ansible&logoColor=white)](https://docs.ansible.com/) |

Feel free to explore and expand your tech horizons! 🌟

---
## Contributors

<a href="https://github.com/NisargPipaliya/TechTitans/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=NisargPipaliya/TechTitans" />
</a>

## Star History

<a href="https://star-history.com/#NisargPipaliya/TechTitans&Date">
 <picture>
   <source media="(prefers-color-scheme: dark)" srcset="https://api.star-history.com/svg?repos=NisargPipaliya/TechTitans&type=Date&theme=dark" />
   <source media="(prefers-color-scheme: light)" srcset="https://api.star-history.com/svg?repos=NisargPipaliya/TechTitans&type=Date" />
   <img alt="Star History Chart" src="https://api.star-history.com/svg?repos=NisargPipaliya/TechTitans&type=Date" />
 </picture>
</a>

TechTitans &copy;

**Comment by NisargPipaliya** [comment]
**Thank You, we would consider it**
